spring.application.name=api

server.port=8089

# ==========================================
# Spring Security config
# ==========================================
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

#
#  Banco de dados em emmória para produção
#
spring.datasource.url=jdbc:h2:mem:dbagendio
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# CONSOLE H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Caminho da documentaÃ§Ã£o OpenAPI
springdoc.api-docs.path=/v3/api-docs

# Caminho da interface Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# OrdenaÃ§Ã£o das operaÃ§Ãµes
springdoc.swagger-ui.operations-sorter=method

# OrdenaÃ§Ã£o das tags
springdoc.swagger-ui.tags-sorter=alpha

# Expande os detalhes das operaÃ§Ãµes
springdoc.swagger-ui.doc-expansion=none